PREFIX cap: <https://hcis.io/ontology/aicapstone/2026/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?obj ?type ?label ?role ?affordance
WHERE {
  ?obj a ?type .
  ?type rdfs:subClassOf* cap:PhysicalObject .
  OPTIONAL { ?obj cap:hasObjectLabel ?label . }
  OPTIONAL { ?obj cap:hasTaskRole ?role . }
  OPTIONAL { ?obj cap:hasAffordance ?affordance . }
}
ORDER BY ?obj