#!/usr/bin/env python3
"""
Headless OWL DL reasoning + SPARQL workflow for Group 13's HW5 submission.

Steps:
  1. Merge group-ontology.ttl + imports into one in-memory graph (owl:imports
     stripped so the reasoner does not try to resolve relative IRIs).
  2. Run the HermiT OWL 2 DL reasoner (via owlready2; uses the local JRE).
  3. Export the *inferred* rdf:type cap:GraspableObject triples to
     ontology/inferred-results.ttl.
  4. Run queries/graspable_objects.rq over (asserted + inferred) and save the
     formatted result table to results/graspable_objects_output.txt.

Run from the repository root:  python3 src/run_reasoning.py
"""
import os
import tempfile
from rdflib import Graph, Namespace, RDF, URIRef
import owlready2

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAP = Namespace("https://hcis.io/ontology/aicapstone/2026/")
G13 = Namespace("https://hcis.io/ontology/aicapstone/2026/group13/")
OWL_IMPORTS = URIRef("http://www.w3.org/2002/07/owl#imports")

GROUP = os.path.join(REPO, "ontology", "group-ontology.ttl")
AFFORD = os.path.join(REPO, "ontology", "imports", "course-affordance.ttl")
ALIGN = os.path.join(REPO, "ontology", "imports", "course-alignment.ttl")
INFERRED = os.path.join(REPO, "ontology", "inferred-results.ttl")
QUERY = os.path.join(REPO, "queries", "graspable_objects.rq")
OUTPUT = os.path.join(REPO, "results", "graspable_objects_output.txt")


def main():
    # --- 1. merge graphs, strip owl:imports ---
    merged = Graph()
    for f in (GROUP, AFFORD, ALIGN):
        merged.parse(f, format="turtle")
    for s, _, o in list(merged.triples((None, OWL_IMPORTS, None))):
        merged.remove((s, OWL_IMPORTS, o))

    asserted_graspable = set(merged.subjects(RDF.type, CAP.GraspableObject))

    with tempfile.NamedTemporaryFile("w", suffix=".owl", delete=False) as tmp:
        tmp_path = tmp.name
    merged.serialize(destination=tmp_path, format="xml")

    # --- 2. run HermiT ---
    world = owlready2.World()
    onto = world.get_ontology("file://" + tmp_path).load()
    with onto:
        owlready2.sync_reasoner_hermit(world, infer_property_values=True)

    gobj = world[str(CAP.GraspableObject)]
    inferred_iris = sorted({ind.iri for ind in gobj.instances()})
    print("Reasoner classified as cap:GraspableObject:")
    for iri in inferred_iris:
        print("   ", iri)

    # --- 3. write inferred-results.ttl (only the inferred type triples) ---
    out = Graph()
    out.bind("cap", CAP)
    out.bind("g13", G13)
    for iri in inferred_iris:
        node = URIRef(iri)
        out.add((node, RDF.type, CAP.GraspableObject))
    header = (
        "# Inferred results for Group 13 HW5.\n"
        "# Generated by src/run_reasoning.py using the HermiT OWL 2 DL reasoner.\n"
        "# Contains the cap:GraspableObject class memberships that were INFERRED\n"
        "# from the equivalent-class axiom in group-ontology.ttl, not asserted.\n\n"
    )
    body = out.serialize(format="turtle")
    with open(INFERRED, "w") as fh:
        fh.write(header + body)
    newly = sorted(set(inferred_iris) - {str(s) for s in asserted_graspable})
    print(f"\nWrote {INFERRED}")
    print(f"  ({len(newly)} inferred, {len(asserted_graspable)} asserted before reasoning)")

    # --- 4. run the required SPARQL query over asserted + inferred ---
    q = Graph()
    for f in (GROUP, AFFORD):
        q.parse(f, format="turtle")
    q.parse(INFERRED, format="turtle")
    with open(QUERY) as fh:
        query_text = fh.read()
    rows = list(q.query(query_text))

    def short(term):
        if term is None:
            return ""
        t = str(term)
        if t.startswith(str(G13)):
            return "g13:" + t[len(str(G13)):]
        if t.startswith(str(CAP)):
            return "cap:" + t[len(str(CAP)):]
        return t

    lines = []
    lines.append("# Output of queries/graspable_objects.rq over the inferred model")
    lines.append("# (asserted group-ontology + course-affordance + inferred-results)")
    lines.append("# Engine: rdflib SPARQL; inference: HermiT OWL 2 DL.")
    lines.append("")
    header_cols = ["obj", "label", "role"]
    table = [header_cols] + [[short(r.obj), short(r.label), short(r.role)] for r in rows]
    widths = [max(len(row[i]) for row in table) for i in range(3)]
    sep = "-+-".join("-" * w for w in widths)
    for i, row in enumerate(table):
        lines.append(" | ".join(row[j].ljust(widths[j]) for j in range(3)))
        if i == 0:
            lines.append(sep)
    lines.append("")
    lines.append(f"# {len(rows)} graspable objects retrieved.")
    text = "\n".join(lines) + "\n"
    with open(OUTPUT, "w") as fh:
        fh.write(text)
    print(f"\nWrote {OUTPUT}\n")
    print(text)

    os.unlink(tmp_path)


if __name__ == "__main__":
    main()
