#!/usr/bin/env python3
"""
SHACL structural validation for Group 13's HW5 submission.

OWL reasoning (see run_reasoning.py) DERIVES class membership such as
cap:GraspableObject. SHACL, by contrast, VALIDATES that the asserted graph
satisfies the structural constraints the course tasks expect (every physical
object has a label, a task role, and an affordance; every manipulation target
has a grasping affordance).

Reads:
  ontology/group-ontology.ttl + ontology/imports/course-affordance.ttl  (data)
  ontology/shapes.ttl                                                    (shapes)
Writes:
  results/shacl_validation_report.txt

Run from the repository root:  python3 src/run_validation.py
"""
import os
from rdflib import Graph
from pyshacl import validate

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GROUP = os.path.join(REPO, "ontology", "group-ontology.ttl")
AFFORD = os.path.join(REPO, "ontology", "imports", "course-affordance.ttl")
SHAPES = os.path.join(REPO, "ontology", "shapes.ttl")
REPORT = os.path.join(REPO, "results", "shacl_validation_report.txt")


def main():
    data = Graph()
    data.parse(GROUP, format="turtle")
    data.parse(AFFORD, format="turtle")

    shapes = Graph()
    shapes.parse(SHAPES, format="turtle")

    conforms, _, report_text = validate(
        data,
        shacl_graph=shapes,
        inference="rdfs",      # materialise rdf:type so targetClass/sh:class match
        advanced=True,         # enable SHACL-SPARQL targets
        meta_shacl=False,
        debug=False,
    )

    header = (
        "# SHACL validation report for Group 13 HW5.\n"
        "# Generated by src/run_validation.py (pyshacl).\n"
        "# Data:   ontology/group-ontology.ttl + imports/course-affordance.ttl\n"
        "# Shapes: ontology/shapes.ttl\n"
        f"# Conforms: {conforms}\n\n"
    )
    with open(REPORT, "w") as fh:
        fh.write(header + report_text)

    print(header + report_text)
    print(f"Wrote {REPORT}")
    return 0 if conforms else 1


if __name__ == "__main__":
    raise SystemExit(main())
